/* 
 * 
 * iviLINK SDK, version 1.1.2
 * http://www.ivilink.net
 * Cross Platform Application Communication Stack for In-Vehicle Applications
 * 
 * Copyright (C) 2012, Luxoft Professional Corp., member of IBS group
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; version 2.1.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 * 
 * 
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luxoft_ivilink_DeviceManager_TrustListActivity */

#ifndef _Included_com_luxoft_ivilink_sdk_DeviceManager_TrustListActivity
#define _Included_com_luxoft_ivilink_sdk_DeviceManager_TrustListActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luxoft_ivilink_DeviceManager_TrustListActivity
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_sdk_DeviceManager_TrustListActivity_start
  (JNIEnv *, jobject callbacks, jstring trustListPath);

/*
 * Class:     com_luxoft_ivilink_DeviceManager_TrustListActivity
 * Method:    removeDeviceFromList
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_sdk_DeviceManager_TrustListActivity_removeDeviceFromList
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_luxoft_ivilink_DeviceManager_TrustListActivity
 * Method:    trustListClear()
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_sdk_DeviceManager_TrustListActivity_trustListClear
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_DeviceManager_TrustListActivity
 * Method:    disconnectDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_sdk_DeviceManager_TrustListActivity_disconnectDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_luxoft_ivilink_DeviceManager_TrustListActivity
 * Method:    isConnected
 * Signature: ()B
 */
JNIEXPORT bool JNICALL Java_com_luxoft_ivilink_sdk_DeviceManager_TrustListActivity_isConnected
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_DeviceManager_TrustListActivity
 * Method:    trustDbReload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_sdk_DeviceManager_TrustListActivity_trustDbReload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
