######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 4 15:00:40 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += phonon


DEFINES += USELOG4CPLUS
INCLUDEPATH += "../../../../src_products/3rd_party/include"
INCLUDEPATH += "../../.."

# Input
HEADERS += NaviPlayer.hpp
SOURCES += main.cpp NaviPlayer.cpp
