/* 
 *   This file is part of iviLINK 0.9 Technology Preview Samples Set.          
 *                                                                             
 *   iviLINK 0.9 Technology Preview Samples Set is free software:              
 *   you can redistribute it and/or modify                                     
 *   it under the terms of the GNU General Public License as published by      
 *   the Free Software Foundation, version 3 of the License.                   
 *                                                                             
 *   iviLINK 0.9 Technology Preview Samples Set is distributed in the          
 *   hope that it will be useful, but WITHOUT ANY WARRANTY; without            
 *   even the implied warranty of MERCHANTABILITY or FITNESS FOR A             
 *   PARTICULAR PURPOSE.  See the GNU General Public License for more details. 
 *                                                                              
 *   You should have received a copy of the GNU General Public License         
 *   along with iviLINK 0.9 Technology Preview.                                
 *   If not, see <http://www.gnu.org/licenses/>.                               
 * 
 */




// checksum 0x898f version 0x70013
/*
  This file was generated by the Qt Quick Application wizard of Qt Creator.
  QmlApplicationViewer is a convenience class containing mobile device specific
  code such as screen orientation handling. Also QML paths and debugging are
  handled here.
  It is recommended not to modify this file, since newer versions of Qt Creator
  may offer an updated version of it.
*/

#ifndef QMLAPPLICATIONVIEWER_H
#define QMLAPPLICATIONVIEWER_H

#include <QtDeclarative/QDeclarativeView>

class QmlApplicationViewer : public QDeclarativeView
{
    Q_OBJECT

public:
    enum ScreenOrientation {
        ScreenOrientationLockPortrait,
        ScreenOrientationLockLandscape,
        ScreenOrientationAuto
    };

    explicit QmlApplicationViewer(QWidget *parent = 0);
    virtual ~QmlApplicationViewer();

    static QmlApplicationViewer *create();

    void setMainQmlFile(const QString &file);
    void addImportPath(const QString &path);

    // Note that this will only have an effect on Symbian and Fremantle.
    void setOrientation(ScreenOrientation orientation);

    void showExpanded();

private:
    class QmlApplicationViewerPrivate *d;
};

QApplication *createApplication(int &argc, char **argv);

#endif // QMLAPPLICATIONVIEWER_H
