/* 
 * iviLINK SDK, version 1.2
 * http://www.ivilink.net
 * Cross Platform Application Communication Stack for In-Vehicle Applications
 * 
 * Copyright (C) 2012-2013, Luxoft Professional Corp., member of IBS group
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; version 2.1.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 * 
 */ 


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luxoft_ivilink_samples_climate_BridgeC */

#ifndef _Included_com_luxoft_ivilink_samples_climate_BridgeC
#define _Included_com_luxoft_ivilink_samples_climate_BridgeC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    offPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_offPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    autoPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_autoPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    acPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_acPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    dualPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_dualPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    recircPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_recircPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    frontPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_frontPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    rearPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_rearPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    fanDownPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_fanDownPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    fanMiddlePressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_fanMiddlePressed
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    fanTopPressed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_fanTopPressed
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    fanIncrease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_fanIncrease
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    fanDecrease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_fanDecrease
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    drvTempUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_drvTempUp
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    drvTempDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_drvTempDown
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    passTempUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_passTempUp
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    passTempDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_passTempDown
  (JNIEnv *, jobject);

/*
 * Class:     com_luxoft_ivilink_samples_climate_BridgeC
 * Method:    startApp
 * Signature: (Ljava/lang/String;Lcom/luxoft/ivilink/samples/climate/BridgeJava;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_startApp
  (JNIEnv *, jobject, jstring, jstring, jstring);

JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_saveState
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_luxoft_ivilink_samples_climate_Bridge_reloadState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
