# framework config 

export FW_DIR := $(IVILINK_FW_DIR)
export RESULT_DIR := $(abspath $(FW_DIR)products)
export PREFIX := $(abspath $(ROOT_DIR)iviLink)
export UTILS_DIR := $(IVILINK_INCLUDE_UTILS_DIR)
export MISC_DIR := $(UTILS_DIR)misc/
export THREADS_DIR := $(UTILS_DIR)threads/
export UNITTEST_DIR := $(FW_DIR)tests/unit/

export SYSTEM_CONTROLLER_PROCESS_NAME := IVILinkSystemController
export CONNECTIVITY_AGENT_PROCESS_NAME := IVILinkConnectivityAgent
export APPLICATION_MANAGER_PROCESS_NAME := IVILinkApplicationManager
export NEGOTIATOR_PROCESS_NAME := IVILinkNegotiator
export PROFILE_MANAGER_PROCESS_NAME := IVILinkProfileManager
export PROFILE_REPOSITORY_PROCESS_NAME := IVILinkProfileRepository
export CONNECTIVITY_AGENT_LIBRARY_NAME := libConnectivityAgent.so
export SYSTEM_CONTROLLER_WATCHDOG_PROCESS_NAME := IVILinkSystemControllerWatchdog
export AUTHENTICATION_APPLICATION_PROCESS_NAME := AuthenticationApplication
export IVILINK_REPOSITORY := $(PREFIX)/database/
export IVILINK_PROFILE_API_REPOSITORY := $(IVILINK_REPOSITORY)profileAPIs/
export IVILINK_PROFILE_REPOSITORY := $(IVILINK_REPOSITORY)profiles/
export IVILINK_SERVICE_REPOSITORY := $(IVILINK_REPOSITORY)services/
export IVILINK_APPLICATION_REPOSITORY := $(IVILINK_REPOSITORY)applications/
export PROGRESSBAR_PROCESS_NAME := IVILinkProgressBar

export BIN_DIR := bin
export OBJ_DIR := obj

GLOBAL_CFLAGS   := -I$(ROOT_DIR) -Wall -pthread -fPIC -I$(3RD_PARTY_RES_DIR)include -I$(MISC_DIR) -I$(THREADS_DIR) #-Werror

#NONUNIQUE_AXIS_QUEUE:=true
ifeq ($(NONUNIQUE_AXIS_QUEUE),true) 
# Set server and client daemons listen on different sockets.
GLOBAL_CFLAGS += -DNONUNIQUE_AXIS_QUEUE
endif

GLOBAL_LDFLAGS  := -L$(ROOT_DIR) -lrt -pthread -L$(IVILINK_LIB_DIR) -L$(3RD_PARTY_RES_DIR)lib -Wl,-rpath,$(PREFIX)

export  USELOG4CPLUS:=true
export  USELOG4CPLUS_DYNAMIC:=true
ifeq ($(USELOG4CPLUS),true)
GLOBAL_CFLAGS += -DUSELOG4CPLUS
ifeq ($(USELOG4CPLUS_DYNAMIC),true)
GLOBAL_LDFLAGS += -llog4cplus -Wl,-rpath
else
GLOBAL_LDFLAGS += -Wl,-Bstatic -llog4cplus -Wl,-Bdynamic
endif # USELOG4CPLUS_DYNAMIC
endif # USELOG4CPLUS

GLOBAL_CFLAGS += -DPREFIX='"$(PREFIX)/"'
GLOBAL_CFLAGS += -DIVILINK_BIN_DIR='"$(IVILINK_BIN_DIR)"'
GLOBAL_CFLAGS += -DIVILINK_APP_DIR='"$(IVILINK_APP_DIR)"'

GLOBAL_CFLAGS += -DSYSTEM_CONTROLLER_PROCESS_NAME='"$(SYSTEM_CONTROLLER_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DCONNECTIVITY_AGENT_PROCESS_NAME='"$(CONNECTIVITY_AGENT_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DAPPLICATION_MANAGER_PROCESS_NAME='"$(APPLICATION_MANAGER_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DNEGOTIATOR_PROCESS_NAME='"$(NEGOTIATOR_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DPROFILE_MANAGER_PROCESS_NAME='"$(PROFILE_MANAGER_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DPROFILE_REPOSITORY_PROCESS_NAME='"$(PROFILE_REPOSITORY_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DSYSTEM_CONTROLLER_WATCHDOG_PROCESS_NAME='"$(SYSTEM_CONTROLLER_WATCHDOG_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DPROFILE_REPOSITORY='"$(IVILINK_PROFILE_REPOSITORY)"'
GLOBAL_CFLAGS += -DSERVICE_REPOSITORY='"$(IVILINK_SERVICE_REPOSITORY)"'
GLOBAL_CFLAGS += -DAPPLICATION_MANAGER_REPOSITORY='"$(APPLICATION_MANAGER_REPOSITORY)"'
GLOBAL_CFLAGS += -DPROGRESSBAR_PROCESS_NAME='"$(PROGRESSBAR_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DAUTHENTICATION_APPLICATION_PROCESS_NAME='"$(AUTHENTICATION_APPLICATION_PROCESS_NAME)"'

# handy for testing, when components are launched manually
export NO_SYSTEM_CONTROLLER_LAUNCH :=false
ifeq ($(NO_SYSTEM_CONTROLLER_LAUNCH),true)
GLOBAL_CFLAGS +=-DNO_SYSTEM_CONTROLLER_LAUNCH
endif

ifeq ($(TEST),true)
GLOBAL_CFLAGS += -DIVILINK_UNITTESTBUILD
endif

GLOBAL_CXXFLAGS := $(GLOBAL_CFLAGS)

GLOBAL_DLL_CFLAGS   := 
GLOBAL_DLL_CXXFLAGS := $(GLOBAL_DLL_CFLAGS)
GLOBAL_DLL_LDFALGS  :=  


export GLOBAL_CFLAGS
export GLOBAL_CXXFLAGS
export GLOBAL_LDFLAGS
export GLOBAL_DLL_CFLAGS
export GLOBAL_DLL_CXXFLAGS
export GLOBAL_DLL_LDFALGS

export NOTHING:=
export SPACE:=$(NOTHING) $(NOTHING)
export COMMA:=,

export FWCONFIG_MK_EXPORTED=true
