/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luxoft_ivilink_sdk_android_nonnative_ConnectionInformation */

#ifndef _Included_com_luxoft_ivilink_sdk_android_nonnative_ConnectionInformation
#define _Included_com_luxoft_ivilink_sdk_android_nonnative_ConnectionInformation
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     com_luxoft_ivilink_sdk_android_nonnative_ConnectionInformation
 * Method:    getConnectionInformationNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luxoft_ivilink_sdk_android_nonnative_ConnectionInformation_getConnectionInformationNative
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
