/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luxoft_ivilink_sdk_android_nonnative_ProfileGetter */

#ifndef _Included_com_luxoft_ivilink_sdk_android_nonnative_ProfileGetter
#define _Included_com_luxoft_ivilink_sdk_android_nonnative_ProfileGetter
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     com_luxoft_ivilink_sdk_android_nonnative_ProfileGetter
 * Method:    getProfile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_luxoft_ivilink_sdk_android_nonnative_ProfileGetter_getProfileNative(
        JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_luxoft_ivilink_sdk_android_nonnative_ProfileGetter
 * Method:    releaseProfile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_sdk_android_nonnative_ProfileGetter_releaseProfileNative
(JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
