
/**
 *
 */

/**
 * @ingroup iOS Port
 * @author Bratanova Elena <ebratanova@luxoft.com>
 * @date 29.03.2013
 *
 * Autogenerated stub.
 */

#import <UIKit/UIKit.h>

@interface ViewController : UIViewController

@end
