# $Id: config.mk 894 2011-11-30 17:47:06Z pilin $

export ROOT_DIR := $(realpath $(dir $(lastword $(MAKEFILE_LIST))))/
$(info ROOT_DIR $(ROOT_DIR))

COMMON_MK := $(ROOT_DIR)common.mk
include $(COMMON_MK)
export COMMON_MK

export TOOLS_DIR := $(ROOT_DIR)tools

export IDL_GEN := $(TOOLS_DIR)/idl_gen/axis_gen


#export LIB_DIR := lib
export BIN_DIR := bin
export OBJ_DIR := obj

#export RESULT_DIR := .
export RESULT_DIR := $(abspath $(ROOT_DIR)../src_products)
export 3RD_PARTY_DIR := $(RESULT_DIR)/3rd_party
export PREFIX := $(abspath $(ROOT_DIR)../src_install)

export SYSTEM_CONTROLLER_PROCESS_NAME := IVILinkSystemController
export CONNECTIVITY_AGENT_PROCESS_NAME := IVILinkConnectivityAgent
export APPLICATION_MANAGER_PROCESS_NAME := IVILinkApplicationManager
export NEGOTIATOR_PROCESS_NAME := IVILinkNegotiator
export PROFILE_MANAGER_PROCESS_NAME := IVILinkProfileManager
export PROFILE_REPOSITORY_PROCESS_NAME := IVILinkProfileRepository
export CONNECTIVITY_AGENT_LIBRARY_NAME := libConnectivityAgent.so

export PROFILE_REPOSITORY := $(PREFIX)/profile_repository
export SERVICE_REPOSITORY := $(PREFIX)/service_repository
export APPLICATION_MANAGER_REPOSITORY := $(PREFIX)/application_manager_repository

GLOBAL_CFLAGS   := -I$(ROOT_DIR) -Wall -pthread -ggdb -fPIC -I$(3RD_PARTY_DIR)/include #-Werror

#NONUNIQUE_AXIS_QUEUE:=true
ifeq ($(NONUNIQUE_AXIS_QUEUE),true) 
# Set server and client daemons listen on different sockets.
GLOBAL_CFLAGS += -DNONUNIQUE_AXIS_QUEUE
endif

GLOBAL_LDFLAGS  := -L$(ROOT_DIR) -lrt -pthread -L$(3RD_PARTY_DIR)/lib -Wl,-rpath,$(PREFIX)

export  USELOG4CPLUS:=true
export  USELOG4CPLUS_DYNAMIC:=true
ifeq ($(USELOG4CPLUS),true)
GLOBAL_CFLAGS += -DUSELOG4CPLUS
ifeq ($(USELOG4CPLUS_DYNAMIC),true)
GLOBAL_LDFLAGS += -llog4cplus -Wl,-rpath,$(3RD_PARTY_DIR)/lib
else
GLOBAL_LDFLAGS += -Wl,-Bstatic -llog4cplus -Wl,-Bdynamic
endif # USELOG4CPLUS_DYNAMIC
endif # USELOG4CPLUS

GLOBAL_CFLAGS += -DPREFIX='"$(PREFIX)/"'

GLOBAL_CFLAGS += -DSYSTEM_CONTROLLER_PROCESS_NAME='"$(SYSTEM_CONTROLLER_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DCONNECTIVITY_AGENT_PROCESS_NAME='"$(CONNECTIVITY_AGENT_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DAPPLICATION_MANAGER_PROCESS_NAME='"$(APPLICATION_MANAGER_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DNEGOTIATOR_PROCESS_NAME='"$(NEGOTIATOR_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DPROFILE_MANAGER_PROCESS_NAME='"$(PROFILE_MANAGER_PROCESS_NAME)"'
GLOBAL_CFLAGS += -DPROFILE_REPOSITORY_PROCESS_NAME='"$(PROFILE_REPOSITORY_PROCESS_NAME)"'

GLOBAL_CFLAGS += -DPROFILE_REPOSITORY='"$(PROFILE_REPOSITORY)"'
GLOBAL_CFLAGS += -DSERVICE_REPOSITORY='"$(SERVICE_REPOSITORY)"'
GLOBAL_CFLAGS += -DAPPLICATION_MANAGER_REPOSITORY='"$(APPLICATION_MANAGER_REPOSITORY)"'


# handy for testing, when components are launched manually
export NO_SYSTEM_CONTROLLER_LAUNCH :=false
ifeq ($(NO_SYSTEM_CONTROLLER_LAUNCH),true)
GLOBAL_CFLAGS +=-DNO_SYSTEM_CONTROLLER_LAUNCH
endif

GLOBAL_CXXFLAGS := $(GLOBAL_CFLAGS)

GLOBAL_DLL_CFLAGS   := 
GLOBAL_DLL_CXXFLAGS := $(GLOBAL_DLL_CFLAGS)
GLOBAL_DLL_LDFALGS  :=  


export GLOBAL_CFLAGS
export GLOBAL_CXXFLAGS
export GLOBAL_LDFLAGS
export GLOBAL_DLL_CFLAGS
export GLOBAL_DLL_CXXFLAGS
export GLOBAL_DLL_LDFALGS

export NOTHING:=
export SPACE:=$(NOTHING) $(NOTHING)
export COMMA:=,

export CONFIG_MK_EXPORTED=true
