/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luxoft_ivilink_sdk_SystemControllerWatchdog */

#ifndef _Included_com_luxoft_ivilink_sdk_SystemControllerWatchdog
#define _Included_com_luxoft_ivilink_sdk_SystemControllerWatchdog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luxoft_ivilink_sdk_SystemControllerWatchdog
 * Method:    startWD
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_luxoft_ivilink_sdk_SystemControllerWatchdog_startWD
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
